CREATE TABLE USER_TYPE (
                        	IDT_USER_ID INTEGER PRIMARY KEY NOT NULL, USER_TYPE VARCHAR(30)
);

CREATE TABLE PERSON (
                     	IDT_PERSON_ID INTEGER PRIMARY KEY NOT NULL,
                        NAM_PERSON VARCHAR(50),
                        LOGIN VARCHAR(50),
                        PASSWORD VARCHAR(50),
                        USER_ID INTEGER,
                        CONSTRAINT USER_PERSON_FK FOREIGN KEY(USER_ID) REFERENCES USER_TYPE(IDT_USER_ID)
);

CREATE TABLE ACTOR (
                    	IDT_ACTOR_ID INTEGER PRIMARY KEY NOT NULL,
                        NAM_ACTOR VARCHAR(50),
                        AGE_ACTOR INTEGER
);

CREATE TABLE NAME_CAST (
                        	IDT_NAME_CAST_ID INTEGER PRIMARY KEY NOT NULL,
                            ACTOR_ID INTEGER,
                            CONSTRAINT NAME_CAST_ACTOR_FK FOREIGN KEY(ACTOR_ID) REFERENCES ACTOR(IDT_ACTOR_ID),
                            TITLE_ID INTEGER
);

CREATE TABLE DIRECTOR (
                       		IDT_DIRECTOR_ID INTEGER PRIMARY KEY NOT NULL,
                            NAM_DIRECTOR VARCHAR(50), DIRECTOR_AGE INTEGER
);

CREATE TABLE DIRECTION (
                        	IDT_DIRECTION_ID INTEGER PRIMARY KEY NOT NULL,
                            DIRECTOR_ID INTEGER,
                            CONSTRAINT DIRECTION_DIRECTOR_FK FOREIGN KEY(DIRECTOR_ID) REFERENCES DIRECTOR(IDT_DIRECTOR_ID)
);

CREATE TABLE GENRE (
                    	IDT_GENRE_ID INTEGER PRIMARY KEY NOT NULL,
                        NAM_GENRE VARCHAR(30)
);

CREATE TABLE TITLE_TYPE (
                         	IDT_TITLE_TYPE_ID INTEGER PRIMARY KEY NOT NULL,
                         	NAM_TYPE VARCHAR(30)
);

CREATE TABLE TITLE (
                    	IDT_TITLE_ID INTEGER PRIMARY KEY NOT NULL, CLASSIFICATION VARCHAR(30), LAUNCH DATE,
                     	NAM_TITLE VARCHAR(50),
                        VAL_DURATION VARCHAR(30),
                        DIRECTION_ID INTEGER,
                        CONSTRAINT TITLE_DIRECTION_FK FOREIGN KEY(DIRECTION_ID) REFERENCES DIRECTION(IDT_DIRECTION_ID),
                        NAM_CAST_ID INTEGER,
                        CONSTRAINT TITLE_NAME_CAST_FK FOREIGN KEY(NAM_CAST_ID) REFERENCES NAME_CAST(IDT_NAME_CAST_ID),
                        GENRE_ID INTEGER,
                        CONSTRAINT TITLE_GENRE_FK FOREIGN KEY(GENRE_ID) REFERENCES GENRE(IDT_GENRE_ID),
                        TITLE_TYPE_ID INTEGER,
                        CONSTRAINT TITLE_TITLE_TYPE_FK FOREIGN KEY(TITLE_TYPE_ID) REFERENCES TITLE_TYPE(IDT_TITLE_TYPE_ID)
 );

CREATE TABLE HISTORY (
                            IDT_HISTORY_ID INTEGER PRIMARY KEY NOT NULL,
                            DAT_HISTORY DATE,
                            PERSON_ID INTEGER,
                            CONSTRAINT HISTORY_PERSON_FK FOREIGN KEY(PERSON_ID) REFERENCES PERSON(IDT_PERSON_ID),
                            TITLE_ID INTEGER,
                            CONSTRAINT HISTORY_TITLE_FK FOREIGN KEY(TITLE_ID) REFERENCES TITLE(IDT_TITLE_ID)
);

ALTER TABLE NAME_CAST ADD CONSTRAINT NAME_CAST_TITLE_FK
            FOREIGN KEY(TITLE_ID) REFERENCES TITLE(IDT_TITLE_ID)
;


